config/routes.rb
SfdcRailsDemo::Application.routes.draw do
  get "accounts/index"
  get "accounts/search"
  match "/accounts/:id", to: "accounts#show", as: 'account'

  root :to => 'accounts#index'

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  
  include Databasedotcom::Rails::Controller
  
  def index
    @accounts = Account.all
  end

  def show
    @account = Account.find(params[:id])
  end

  def search
    config = YAML.load_file(File.join(::Rails.root, 'config', 'databasedotcom.yml'))
    client = Databasedotcom::Client.new(config)          
    client.authenticate :username => config[:username], :password => config[:password]
    @accounts = client.query("select id, name from account where name like 'United%'")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/index.html.erb
<ul>
	<% @accounts.each do |account| %>
	<li><%= link_to account.Name, account_path(account.Id) %></li>
	<% end %>
</ul>

app/views/accounts/search.html.erb
<ul>
	<% @accounts.each do |account| %>
	<li><%= link_to account.Name, account_path(account.Id) %></li>
	<% end %>
</ul>

app/views/accounts/show.html.erb
<h1><%= @account.Name %></h1>

<%= @account.Type %><br>
<%= @account.Industry %><br>
<%= @account.Phone %><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SfdcRailsDemo</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>